version: "3.9"

services:
    api:
        build:
            dockerfile: Dockerfile
            context: ./back
        depends_on:
            - postgres
            - redis
        environment:
            DATABASE_URL: postgres://postgres:123456@postgres:5432/file_converter
            REDIS_URL: redis://redis:6379/0
        ports:
            - "8000:8000"
        volumes:
            - uploaded-files:/back/uploads
            - converted-files:/back/results

    postgres:
        image: postgres
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: "123456"
            POSTGRES_DB: file_converter
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        container_name: redis
        image: redis:latest
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

    celery:
        container_name: celery
        build:
            context: ./celery_app
            dockerfile: Dockerfile
        depends_on:
            - redis
            - postgres
        environment:
            REDIS_HOST: redis
            REDIS_PORT: "6379"
            DATABASE_URL: postgres://postgres:123456@postgres:5432/file_converter
        volumes:
            - uploaded-files:/back/uploads
            - converted-files:/back/results

    frontend:
        build:
            context: ./front
            dockerfile: Dockerfile
        ports:
            - "3000:3000"

volumes:
    redis-data:
    postgres-data:
        driver: local
    converted-files:
    uploaded-files:
